
<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Zend Framework 2</span></h1>
    <p>Congratulations! You have successfully installed the <a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">ZF2 Skeleton Application</a>. You are currently running Zend Framework version 2.2.3. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.</p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank">Fork Zend Framework 2 on GitHub »</a></p>
    <p>index album</p>
</div>